- params:
    git:
      repoName: hello-world-java
      gitProvider: github
      token: ${{ secrets.GITHUB_TOKEN }}
      branches:
        - master
    scan:
      emailReceivers:
        - javed.faruquee@hotmail.com
      projects:
        - workingDirs:
            - .
