- params:
    git:
      repoName: javedfaruquee1/hello-world-java
      gitProvider: github
      GITHUB_USERNAME: ${{ secrets.GIT_USERNAME }}
      token: ${{ secrets.GITHUB_TOKEN }}
      branches:
        - master
    scan:
      emailReceivers:
        - javed.faruquee@hexagon.com
      projects:
        - workingDirs:
            - action
        - workingDirs:
            - .
